server:
  port: 9004

spring:
  application:
    name: xdclass-order-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 47.115.119.249:8848

  #消息队列
  rabbitmq:
    host: 192.168.0.101
    port: 5672
    virtual-host: /
    password: password
    username: admin
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#redis 配置
  redis:
    host: 192.168.0.101
    port: 8000
    password: 123456


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO


